version: '3.9'

x-common: &common
    restart: unless-stopped

services:
    database:
        image: postgres:15-alpine
        container_name: shorturl-database
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        env_file:
            - .env
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data:rw
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            timeout: 5s
            retries: 3
        <<: *common
