version: "3"

tasks:
  migrate:
    desc: "Run database migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/database.db --migrations-path=./migrations

  run:
    desc: "Run database migrations"
    cmds:
      - go run ./cmd/shortener --storage-path=./storage/database.db
