CREATE TABLE IF NOT EXISTS urls
(
    id   SERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    url  VARCHAR(255) NOT NULL UNIQUE
    );
CREATE INDEX IF NOT EXISTS idx_code ON urls (code);
CREATE INDEX IF NOT EXISTS idx_url ON urls (url);