// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/models/batch_url.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchFullUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId *string                `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	OriginalUrl   *string                `protobuf:"bytes,2,opt,name=original_url,json=originalUrl" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFullUrl) Reset() {
	*x = BatchFullUrl{}
	mi := &file_internal_proto_v1_models_batch_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFullUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFullUrl) ProtoMessage() {}

func (x *BatchFullUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_models_batch_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFullUrl.ProtoReflect.Descriptor instead.
func (*BatchFullUrl) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_models_batch_url_proto_rawDescGZIP(), []int{0}
}

func (x *BatchFullUrl) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *BatchFullUrl) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

type BatchShortUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId *string                `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	ShortUrl      *string                `protobuf:"bytes,2,opt,name=short_url,json=shortUrl" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortUrl) Reset() {
	*x = BatchShortUrl{}
	mi := &file_internal_proto_v1_models_batch_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortUrl) ProtoMessage() {}

func (x *BatchShortUrl) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_models_batch_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortUrl.ProtoReflect.Descriptor instead.
func (*BatchShortUrl) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_models_batch_url_proto_rawDescGZIP(), []int{1}
}

func (x *BatchShortUrl) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *BatchShortUrl) GetShortUrl() string {
	if x != nil && x.ShortUrl != nil {
		return *x.ShortUrl
	}
	return ""
}

var File_internal_proto_v1_models_batch_url_proto protoreflect.FileDescriptor

const file_internal_proto_v1_models_batch_url_proto_rawDesc = "" +
	"\n" +
	"(internal/proto/v1/models/batch_url.proto\x12\x18internal.proto.v1.models\"X\n" +
	"\fBatchFullUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"S\n" +
	"\rBatchShortUrl\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrlB8Z6github.com/vadicheck/shorturl/internal/proto/v1/modelsb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_models_batch_url_proto_rawDescOnce sync.Once
	file_internal_proto_v1_models_batch_url_proto_rawDescData []byte
)

func file_internal_proto_v1_models_batch_url_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_models_batch_url_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_models_batch_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_models_batch_url_proto_rawDesc), len(file_internal_proto_v1_models_batch_url_proto_rawDesc)))
	})
	return file_internal_proto_v1_models_batch_url_proto_rawDescData
}

var file_internal_proto_v1_models_batch_url_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_v1_models_batch_url_proto_goTypes = []any{
	(*BatchFullUrl)(nil),  // 0: internal.proto.v1.models.BatchFullUrl
	(*BatchShortUrl)(nil), // 1: internal.proto.v1.models.BatchShortUrl
}
var file_internal_proto_v1_models_batch_url_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_models_batch_url_proto_init() }
func file_internal_proto_v1_models_batch_url_proto_init() {
	if File_internal_proto_v1_models_batch_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_models_batch_url_proto_rawDesc), len(file_internal_proto_v1_models_batch_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_models_batch_url_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_models_batch_url_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_models_batch_url_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_models_batch_url_proto = out.File
	file_internal_proto_v1_models_batch_url_proto_goTypes = nil
	file_internal_proto_v1_models_batch_url_proto_depIdxs = nil
}
