// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/models/url.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// URL represents a shortened URL entry in the database.
// It contains information about the original URL, its shortened code, and the associated user ID.
type Url struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the unique identifier for the URL entry in the database.
	Id *int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Code is the shortened code associated with the URL.
	Code *string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	// URL is the original URL that has been shortened.
	Url *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	// UserID is the ID of the user who created the shortened URL.
	UserId *string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// IsDeleted indicates whether the URL has been deleted.
	// If true, the URL has been marked as deleted.
	IsDeleted     *string `protobuf:"bytes,5,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_internal_proto_v1_models_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_models_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_models_url_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Url) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Url) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Url) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Url) GetIsDeleted() string {
	if x != nil && x.IsDeleted != nil {
		return *x.IsDeleted
	}
	return ""
}

var File_internal_proto_v1_models_url_proto protoreflect.FileDescriptor

const file_internal_proto_v1_models_url_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/v1/models/url.proto\x12\x18internal.proto.v1.models\"s\n" +
	"\x03Url\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\tR\tisDeletedB8Z6github.com/vadicheck/shorturl/internal/proto/v1/modelsb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_models_url_proto_rawDescOnce sync.Once
	file_internal_proto_v1_models_url_proto_rawDescData []byte
)

func file_internal_proto_v1_models_url_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_models_url_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_models_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_models_url_proto_rawDesc), len(file_internal_proto_v1_models_url_proto_rawDesc)))
	})
	return file_internal_proto_v1_models_url_proto_rawDescData
}

var file_internal_proto_v1_models_url_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_v1_models_url_proto_goTypes = []any{
	(*Url)(nil), // 0: internal.proto.v1.models.Url
}
var file_internal_proto_v1_models_url_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_models_url_proto_init() }
func file_internal_proto_v1_models_url_proto_init() {
	if File_internal_proto_v1_models_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_models_url_proto_rawDesc), len(file_internal_proto_v1_models_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_models_url_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_models_url_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_models_url_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_models_url_proto = out.File
	file_internal_proto_v1_models_url_proto_goTypes = nil
	file_internal_proto_v1_models_url_proto_depIdxs = nil
}
