// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/rpc/batch.proto

package rpc

import (
	models "github.com/vadicheck/shorturl/internal/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*models.BatchFullUrl `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_proto_v1_rpc_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_batch_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetUrls() []*models.BatchFullUrl {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        []*models.BatchShortUrl `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_proto_v1_rpc_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_batch_proto_rawDescGZIP(), []int{1}
}

func (x *BatchResponse) GetResult() []*models.BatchShortUrl {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_proto_v1_rpc_batch_proto protoreflect.FileDescriptor

const file_internal_proto_v1_rpc_batch_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/v1/rpc/batch.proto\x12\x15internal.proto.v1.rpc\x1a(internal/proto/v1/models/batch_url.proto\"J\n" +
	"\fBatchRequest\x12:\n" +
	"\x04urls\x18\x01 \x03(\v2&.internal.proto.v1.models.BatchFullUrlR\x04urls\"P\n" +
	"\rBatchResponse\x12?\n" +
	"\x06result\x18\x01 \x03(\v2'.internal.proto.v1.models.BatchShortUrlR\x06resultB5Z3github.com/vadicheck/shorturl/internal/proto/v1/rpcb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_rpc_batch_proto_rawDescOnce sync.Once
	file_internal_proto_v1_rpc_batch_proto_rawDescData []byte
)

func file_internal_proto_v1_rpc_batch_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_rpc_batch_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_rpc_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_batch_proto_rawDesc), len(file_internal_proto_v1_rpc_batch_proto_rawDesc)))
	})
	return file_internal_proto_v1_rpc_batch_proto_rawDescData
}

var file_internal_proto_v1_rpc_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_v1_rpc_batch_proto_goTypes = []any{
	(*BatchRequest)(nil),         // 0: internal.proto.v1.rpc.BatchRequest
	(*BatchResponse)(nil),        // 1: internal.proto.v1.rpc.BatchResponse
	(*models.BatchFullUrl)(nil),  // 2: internal.proto.v1.models.BatchFullUrl
	(*models.BatchShortUrl)(nil), // 3: internal.proto.v1.models.BatchShortUrl
}
var file_internal_proto_v1_rpc_batch_proto_depIdxs = []int32{
	2, // 0: internal.proto.v1.rpc.BatchRequest.urls:type_name -> internal.proto.v1.models.BatchFullUrl
	3, // 1: internal.proto.v1.rpc.BatchResponse.result:type_name -> internal.proto.v1.models.BatchShortUrl
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_rpc_batch_proto_init() }
func file_internal_proto_v1_rpc_batch_proto_init() {
	if File_internal_proto_v1_rpc_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_batch_proto_rawDesc), len(file_internal_proto_v1_rpc_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_rpc_batch_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_rpc_batch_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_rpc_batch_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_rpc_batch_proto = out.File
	file_internal_proto_v1_rpc_batch_proto_goTypes = nil
	file_internal_proto_v1_rpc_batch_proto_depIdxs = nil
}
