// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/rpc/delete.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_proto_v1_rpc_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_delete_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_proto_v1_rpc_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_delete_proto_rawDescGZIP(), []int{1}
}

var File_internal_proto_v1_rpc_delete_proto protoreflect.FileDescriptor

const file_internal_proto_v1_rpc_delete_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/v1/rpc/delete.proto\x12\x15internal.proto.v1.rpc\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x10\n" +
	"\x0eDeleteResponseB5Z3github.com/vadicheck/shorturl/internal/proto/v1/rpcb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_rpc_delete_proto_rawDescOnce sync.Once
	file_internal_proto_v1_rpc_delete_proto_rawDescData []byte
)

func file_internal_proto_v1_rpc_delete_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_rpc_delete_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_rpc_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_delete_proto_rawDesc), len(file_internal_proto_v1_rpc_delete_proto_rawDesc)))
	})
	return file_internal_proto_v1_rpc_delete_proto_rawDescData
}

var file_internal_proto_v1_rpc_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_v1_rpc_delete_proto_goTypes = []any{
	(*DeleteRequest)(nil),  // 0: internal.proto.v1.rpc.DeleteRequest
	(*DeleteResponse)(nil), // 1: internal.proto.v1.rpc.DeleteResponse
}
var file_internal_proto_v1_rpc_delete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_rpc_delete_proto_init() }
func file_internal_proto_v1_rpc_delete_proto_init() {
	if File_internal_proto_v1_rpc_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_delete_proto_rawDesc), len(file_internal_proto_v1_rpc_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_rpc_delete_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_rpc_delete_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_rpc_delete_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_rpc_delete_proto = out.File
	file_internal_proto_v1_rpc_delete_proto_goTypes = nil
	file_internal_proto_v1_rpc_delete_proto_depIdxs = nil
}
