// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/rpc/get_urls.proto

package rpc

import (
	models "github.com/vadicheck/shorturl/internal/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlsRequest) Reset() {
	*x = GetUrlsRequest{}
	mi := &file_internal_proto_v1_rpc_get_urls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsRequest) ProtoMessage() {}

func (x *GetUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_get_urls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsRequest.ProtoReflect.Descriptor instead.
func (*GetUrlsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_get_urls_proto_rawDescGZIP(), []int{0}
}

type GetUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*models.ShortUrl     `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlsResponse) Reset() {
	*x = GetUrlsResponse{}
	mi := &file_internal_proto_v1_rpc_get_urls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlsResponse) ProtoMessage() {}

func (x *GetUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_get_urls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlsResponse.ProtoReflect.Descriptor instead.
func (*GetUrlsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_get_urls_proto_rawDescGZIP(), []int{1}
}

func (x *GetUrlsResponse) GetUrls() []*models.ShortUrl {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_internal_proto_v1_rpc_get_urls_proto protoreflect.FileDescriptor

const file_internal_proto_v1_rpc_get_urls_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/v1/rpc/get_urls.proto\x12\x15internal.proto.v1.rpc\x1a#internal/proto/v1/models/urls.proto\"\x10\n" +
	"\x0eGetUrlsRequest\"I\n" +
	"\x0fGetUrlsResponse\x126\n" +
	"\x04urls\x18\x01 \x03(\v2\".internal.proto.v1.models.ShortUrlR\x04urlsB5Z3github.com/vadicheck/shorturl/internal/proto/v1/rpcb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_rpc_get_urls_proto_rawDescOnce sync.Once
	file_internal_proto_v1_rpc_get_urls_proto_rawDescData []byte
)

func file_internal_proto_v1_rpc_get_urls_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_rpc_get_urls_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_rpc_get_urls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_get_urls_proto_rawDesc), len(file_internal_proto_v1_rpc_get_urls_proto_rawDesc)))
	})
	return file_internal_proto_v1_rpc_get_urls_proto_rawDescData
}

var file_internal_proto_v1_rpc_get_urls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_v1_rpc_get_urls_proto_goTypes = []any{
	(*GetUrlsRequest)(nil),  // 0: internal.proto.v1.rpc.GetUrlsRequest
	(*GetUrlsResponse)(nil), // 1: internal.proto.v1.rpc.GetUrlsResponse
	(*models.ShortUrl)(nil), // 2: internal.proto.v1.models.ShortUrl
}
var file_internal_proto_v1_rpc_get_urls_proto_depIdxs = []int32{
	2, // 0: internal.proto.v1.rpc.GetUrlsResponse.urls:type_name -> internal.proto.v1.models.ShortUrl
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_rpc_get_urls_proto_init() }
func file_internal_proto_v1_rpc_get_urls_proto_init() {
	if File_internal_proto_v1_rpc_get_urls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_get_urls_proto_rawDesc), len(file_internal_proto_v1_rpc_get_urls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_rpc_get_urls_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_rpc_get_urls_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_rpc_get_urls_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_rpc_get_urls_proto = out.File
	file_internal_proto_v1_rpc_get_urls_proto_goTypes = nil
	file_internal_proto_v1_rpc_get_urls_proto_depIdxs = nil
}
