// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/rpc/internal_stats.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_internal_proto_v1_rpc_internal_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_internal_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_internal_stats_proto_rawDescGZIP(), []int{0}
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          *int32                 `protobuf:"varint,1,opt,name=urls" json:"urls,omitempty"`
	Users         *int32                 `protobuf:"varint,2,opt,name=users" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_internal_proto_v1_rpc_internal_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_rpc_internal_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_rpc_internal_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StatResponse) GetUrls() int32 {
	if x != nil && x.Urls != nil {
		return *x.Urls
	}
	return 0
}

func (x *StatResponse) GetUsers() int32 {
	if x != nil && x.Users != nil {
		return *x.Users
	}
	return 0
}

var File_internal_proto_v1_rpc_internal_stats_proto protoreflect.FileDescriptor

const file_internal_proto_v1_rpc_internal_stats_proto_rawDesc = "" +
	"\n" +
	"*internal/proto/v1/rpc/internal_stats.proto\x12\x15internal.proto.v1.rpc\"\r\n" +
	"\vStatRequest\"8\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05usersB5Z3github.com/vadicheck/shorturl/internal/proto/v1/rpcb\beditionsp\xe8\a"

var (
	file_internal_proto_v1_rpc_internal_stats_proto_rawDescOnce sync.Once
	file_internal_proto_v1_rpc_internal_stats_proto_rawDescData []byte
)

func file_internal_proto_v1_rpc_internal_stats_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_rpc_internal_stats_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_rpc_internal_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_internal_stats_proto_rawDesc), len(file_internal_proto_v1_rpc_internal_stats_proto_rawDesc)))
	})
	return file_internal_proto_v1_rpc_internal_stats_proto_rawDescData
}

var file_internal_proto_v1_rpc_internal_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_v1_rpc_internal_stats_proto_goTypes = []any{
	(*StatRequest)(nil),  // 0: internal.proto.v1.rpc.StatRequest
	(*StatResponse)(nil), // 1: internal.proto.v1.rpc.StatResponse
}
var file_internal_proto_v1_rpc_internal_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_rpc_internal_stats_proto_init() }
func file_internal_proto_v1_rpc_internal_stats_proto_init() {
	if File_internal_proto_v1_rpc_internal_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_rpc_internal_stats_proto_rawDesc), len(file_internal_proto_v1_rpc_internal_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_v1_rpc_internal_stats_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_rpc_internal_stats_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_rpc_internal_stats_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_rpc_internal_stats_proto = out.File
	file_internal_proto_v1_rpc_internal_stats_proto_goTypes = nil
	file_internal_proto_v1_rpc_internal_stats_proto_depIdxs = nil
}
