// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/v1/service.proto

package v1

import (
	rpc "github.com/vadicheck/shorturl/internal/proto/v1/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_proto_v1_service_proto protoreflect.FileDescriptor

const file_internal_proto_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/v1/service.proto\x12\x11internal.proto.v1\x1a#internal/proto/v1/rpc/shorten.proto\x1a!internal/proto/v1/rpc/batch.proto\x1a\"internal/proto/v1/rpc/delete.proto\x1a#internal/proto/v1/rpc/get_url.proto\x1a$internal/proto/v1/rpc/get_urls.proto\x1a internal/proto/v1/rpc/ping.proto\x1a*internal/proto/v1/rpc/internal_stats.proto2\xeb\x04\n" +
	"\bShortURL\x12X\n" +
	"\aShorten\x12%.internal.proto.v1.rpc.ShortenRequest\x1a&.internal.proto.v1.rpc.ShortenResponse\x12R\n" +
	"\x05Batch\x12#.internal.proto.v1.rpc.BatchRequest\x1a$.internal.proto.v1.rpc.BatchResponse\x12U\n" +
	"\x06Delete\x12$.internal.proto.v1.rpc.DeleteRequest\x1a%.internal.proto.v1.rpc.DeleteResponse\x12U\n" +
	"\x06GetURL\x12$.internal.proto.v1.rpc.GetUrlRequest\x1a%.internal.proto.v1.rpc.GetUrlResponse\x12X\n" +
	"\aGetURLs\x12%.internal.proto.v1.rpc.GetUrlsRequest\x1a&.internal.proto.v1.rpc.GetUrlsResponse\x12O\n" +
	"\x04Ping\x12\".internal.proto.v1.rpc.PingRequest\x1a#.internal.proto.v1.rpc.PingResponse\x12X\n" +
	"\rInternalStats\x12\".internal.proto.v1.rpc.StatRequest\x1a#.internal.proto.v1.rpc.StatResponseB1Z/github.com/vadicheck/shorturl/internal/proto/v1b\beditionsp\xe8\a"

var file_internal_proto_v1_service_proto_goTypes = []any{
	(*rpc.ShortenRequest)(nil),  // 0: internal.proto.v1.rpc.ShortenRequest
	(*rpc.BatchRequest)(nil),    // 1: internal.proto.v1.rpc.BatchRequest
	(*rpc.DeleteRequest)(nil),   // 2: internal.proto.v1.rpc.DeleteRequest
	(*rpc.GetUrlRequest)(nil),   // 3: internal.proto.v1.rpc.GetUrlRequest
	(*rpc.GetUrlsRequest)(nil),  // 4: internal.proto.v1.rpc.GetUrlsRequest
	(*rpc.PingRequest)(nil),     // 5: internal.proto.v1.rpc.PingRequest
	(*rpc.StatRequest)(nil),     // 6: internal.proto.v1.rpc.StatRequest
	(*rpc.ShortenResponse)(nil), // 7: internal.proto.v1.rpc.ShortenResponse
	(*rpc.BatchResponse)(nil),   // 8: internal.proto.v1.rpc.BatchResponse
	(*rpc.DeleteResponse)(nil),  // 9: internal.proto.v1.rpc.DeleteResponse
	(*rpc.GetUrlResponse)(nil),  // 10: internal.proto.v1.rpc.GetUrlResponse
	(*rpc.GetUrlsResponse)(nil), // 11: internal.proto.v1.rpc.GetUrlsResponse
	(*rpc.PingResponse)(nil),    // 12: internal.proto.v1.rpc.PingResponse
	(*rpc.StatResponse)(nil),    // 13: internal.proto.v1.rpc.StatResponse
}
var file_internal_proto_v1_service_proto_depIdxs = []int32{
	0,  // 0: internal.proto.v1.ShortURL.Shorten:input_type -> internal.proto.v1.rpc.ShortenRequest
	1,  // 1: internal.proto.v1.ShortURL.Batch:input_type -> internal.proto.v1.rpc.BatchRequest
	2,  // 2: internal.proto.v1.ShortURL.Delete:input_type -> internal.proto.v1.rpc.DeleteRequest
	3,  // 3: internal.proto.v1.ShortURL.GetURL:input_type -> internal.proto.v1.rpc.GetUrlRequest
	4,  // 4: internal.proto.v1.ShortURL.GetURLs:input_type -> internal.proto.v1.rpc.GetUrlsRequest
	5,  // 5: internal.proto.v1.ShortURL.Ping:input_type -> internal.proto.v1.rpc.PingRequest
	6,  // 6: internal.proto.v1.ShortURL.InternalStats:input_type -> internal.proto.v1.rpc.StatRequest
	7,  // 7: internal.proto.v1.ShortURL.Shorten:output_type -> internal.proto.v1.rpc.ShortenResponse
	8,  // 8: internal.proto.v1.ShortURL.Batch:output_type -> internal.proto.v1.rpc.BatchResponse
	9,  // 9: internal.proto.v1.ShortURL.Delete:output_type -> internal.proto.v1.rpc.DeleteResponse
	10, // 10: internal.proto.v1.ShortURL.GetURL:output_type -> internal.proto.v1.rpc.GetUrlResponse
	11, // 11: internal.proto.v1.ShortURL.GetURLs:output_type -> internal.proto.v1.rpc.GetUrlsResponse
	12, // 12: internal.proto.v1.ShortURL.Ping:output_type -> internal.proto.v1.rpc.PingResponse
	13, // 13: internal.proto.v1.ShortURL.InternalStats:output_type -> internal.proto.v1.rpc.StatResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_service_proto_init() }
func file_internal_proto_v1_service_proto_init() {
	if File_internal_proto_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_service_proto_rawDesc), len(file_internal_proto_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_v1_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_service_proto_depIdxs,
	}.Build()
	File_internal_proto_v1_service_proto = out.File
	file_internal_proto_v1_service_proto_goTypes = nil
	file_internal_proto_v1_service_proto_depIdxs = nil
}
